name: CI Frontend
on:
  push:
    branches:
      - karsajobs-ui
jobs:
  lint-dockerfile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Hadolint
        run: sudo wget -O /bin/hadolint https://github.com/hadolint/hadolint/releases/latest/download/hadolint-Linux-x86_64 && sudo chmod +x /bin/hadolint
      - name: Run Hadolint
        run: hadolint Dockerfile

  build-app-karsajobs-ui:
    runs-on: ubuntu-latest
    needs: [lint-dockerfile]
    steps:
      - uses: actions/checkout@v3
      - name: Login to GHCR
        run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      - name: Build & Push
        run: |
          docker build -t ghcr.io/${{ github.repository_owner }}/karsajobs-ui:latest .
          docker push ghcr.io/${{ github.repository_owner }}/karsajobs-ui:latest

